name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
# on: push & pull request  # Default will running for every branch.

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Install Protoc
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter

      # Install protoc-gen-dart
      - run: flutter pub global activate protoc_plugin

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Update submodules
      - run: |
          git submodule init
          git submodule update
      
      # Generate proto stub files
      - run: ./build_proto.sh

      # Copy the config file
      - run: cp config.example.json config.json

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test
